import{a as b,S as w,i as M}from"./assets/vendor-BBPOLzfb.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();b.defaults.baseURL="https://pixabay.com/api/";const O="49397541-1939e7fe1ba522fc58da934d1",S=async(e,r,n=9)=>{if(!e)return{hits:[],totalHits:0};const a={key:O,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,color:"black",per_page:n,page:r};try{const{data:t}=await b.get("",{params:a});return{hits:t.hits.map(({id:o,webformatURL:s,largeImageURL:u,tags:m,likes:f,views:q,comments:H,downloads:$})=>({id:o,webformatURL:s,largeImageURL:u,tags:m,likes:f,views:q,comments:H,downloads:$})),totalHits:t.totalHits}}catch(t){return console.error("Error fetching photos:",t),{hits:[],totalHits:0}}},v=e=>{const r=document.querySelector(".gallery");e.length===0&&(r.innerHTML="");const n=e.map(({webformatURL:a,largeImageURL:t,tags:o,likes:s,views:u,comments:m,downloads:f})=>`
        <li class='gallery-item'>
          <a class='gallery-link' href='${t}'>
            <img class='gallery-image' src='${a}' alt='${o}'>
          </a>
          <ul class='image-info'>
            <li><h4>Likes</h4><p>${s}</p></li>
            <li><h4>Views</h4><p>${u}</p></li>
            <li><h4>Comments</h4><p>${m}</p></li>
            <li><h4>Downloads</h4><p>${f}</p></li>
          </ul>
        </li>`).join("");r.insertAdjacentHTML("beforeend",n),new w(".gallery a",{close:!0,animationSpeed:250,enableKeyboard:!0,showCounter:!0,docClose:!0,captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250})},h=e=>{const r=document.querySelector(".loader");e==="add"?r.classList.remove("is-hidden"):e==="remove"&&r.classList.add("is-hidden")},p=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},P=new w(".js-gallery a");let l=1,d="";const g=15;let y=0,L=0;const x=document.querySelector(".form"),i=document.querySelector(".js-loadmore"),C=async e=>{if(e.preventDefault(),d=e.target.elements["search-text"].value.trim(),l=1,e.target.reset(),!d){c("Sorry, there are no images matching your search query. Please try again!","error"),p(),i.classList.add("is-hidden");return}h("add"),i.classList.add("is-hidden"),p();try{const r=await S(d,l,g);if(!r.hits.length){c("Sorry, there are no images matching your search query. Please try again!","error");return}L=r.totalHits,y=Math.ceil(L/g),v(r.hits),P.refresh(),y>1&&i.classList.remove("is-hidden")}catch(r){c(`Something went wrong: ${r.message}`,"error")}finally{h("remove")}};x.addEventListener("submit",C);const c=(e,r="info")=>{M[r]({message:e,position:"topRight"})};i.addEventListener("click",async()=>{l++,i.classList.add("is-hidden"),h("add");try{const e=await S(d,l,g);v(e.hits),P.refresh(),E(),l>=y?(i.classList.add("is-hidden"),c("We're sorry, but you've reached the end of search results.","info")):i.classList.remove("is-hidden")}catch(e){c(`Something went wrong: ${e.message}`,"error")}finally{h("remove")}});const E=()=>{const e=document.querySelector(".gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
