import{a as L,S as b,i as $}from"./assets/vendor-BBPOLzfb.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const s of o.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&i(s)}).observe(document,{childList:!0,subtree:!0});function n(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function i(t){if(t.ep)return;t.ep=!0;const o=n(t);fetch(t.href,o)}})();L.defaults.baseURL="https://pixabay.com/api/";const M="49397541-1939e7fe1ba522fc58da934d1",S=async(e,r,n=9)=>{if(!e)return{hits:[],totalHits:0};const i={key:M,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,color:"black",per_page:n,page:r};try{const{data:t}=await L.get("",{params:i});return{hits:t.hits.map(({id:o,webformatURL:s,largeImageURL:h,tags:m,likes:f,views:q,comments:P,downloads:H})=>({id:o,webformatURL:s,largeImageURL:h,tags:m,likes:f,views:q,comments:P,downloads:H})),totalHits:t.totalHits}}catch(t){return console.error("Error fetching photos:",t),{hits:[],totalHits:0}}},w=e=>{const r=document.querySelector(".gallery");e.length===0&&(r.innerHTML="");const n=e.map(({webformatURL:i,largeImageURL:t,tags:o,likes:s,views:h,comments:m,downloads:f})=>`
        <li class='gallery-item'>
          <a class='gallery-link' href='${t}'>
            <img class='gallery-image' src='${i}' alt='${o}'>
          </a>
          <ul class='image-info'>
            <li><h4>Likes</h4><p>${s}</p></li>
            <li><h4>Views</h4><p>${h}</p></li>
            <li><h4>Comments</h4><p>${m}</p></li>
            <li><h4>Downloads</h4><p>${f}</p></li>
          </ul>
        </li>`).join("");r.insertAdjacentHTML("beforeend",n),new b(".gallery a",{close:!0,animationSpeed:250,enableKeyboard:!0,showCounter:!0,docClose:!0,captions:!0,captionsData:"alt",captionPosition:"bottom",captionDelay:250})},u=e=>{const r=document.querySelector(".loader");e==="add"?r.classList.remove("is-hidden"):e==="remove"&&r.classList.add("is-hidden")},O=()=>{const e=document.querySelector(".gallery");e.innerHTML=""},v=new b(".js-gallery a");let l=1,d="";const g=15;let y=0,p=0;const j=document.querySelector(".form"),a=document.querySelector(".js-loadmore");document.querySelector(".js-gallery");const x=async e=>{if(e.preventDefault(),d=e.target.elements["search-text"].value.trim(),l=1,e.target.reset(),!d){c("Sorry, there are no images matching your search query. Please try again!","error");return}u("add"),a.classList.add("is-hidden"),O();try{const r=await S(d,l,g);if(!r.hits.length){c("Sorry, there are no images matching your search query. Please try again!","error");return}p=r.totalHits,y=Math.ceil(p/g),w(r.hits),v.refresh(),y>1&&a.classList.remove("is-hidden")}catch(r){c(`Something went wrong: ${r.message}`,"error")}finally{u("remove")}};j.addEventListener("submit",x);const c=(e,r="info")=>{$[r]({message:e,position:"topRight"})};a.addEventListener("click",async()=>{l++,a.classList.add("is-hidden"),u("add");try{const e=await S(d,l,g);w(e.hits),v.refresh(),C(),l>=y?(a.classList.add("is-hidden"),c("We're sorry, but you've reached the end of search results.","info")):a.classList.remove("is-hidden")}catch(e){c(`Something went wrong: ${e.message}`,"error")}finally{u("remove")}});const C=()=>{const e=document.querySelector(".gallery-item");if(!e)return;const r=e.getBoundingClientRect().height;window.scrollBy({top:r*2,behavior:"smooth"})};
//# sourceMappingURL=index.js.map
